name: 'tuva_hcat_ima_rx_connector'
version: '0.0.1'
config-version: 2

profile: 'default'

vars:

  claims_enabled: true
  clinical_enabled: false


### Snowflake Data Sharing
# The copy_grants config is needed for both models and seeds to ensure they
# stay shared after a --full-refresh. The custom macro snowflake__seed_helpers is also required.
models:
  +copy_grants: true
  +database: tuva_hcat_ima_rx
  tuva_hcat_ima_rx_connector:
    +database: tuva_hcat_ima_rx

seeds:
  +copy_grants: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
